name: Models tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    tests:
        # Runs in parallel on specified os in the strategy bellow.
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, windows-latest, ubuntu-latest]
            # Prevent one job from cancelling the others if it fails
            fail-fast: false

        steps:
        - uses: actions/checkout@v3
        - name: Setup Python
          uses: actions/setup-python@v3.1.4
          with:
            # Version range or exact version of a Python version to use, using SemVer's version range syntax.
            python-version: 3.11.3
        - name: Run tests
          run: |
            pip install -r requirements.txt
            python3 src/main.py
    slack:
        # Wait test job to finish
        needs: tests
        if: ${{ always() }}
        runs-on: ubuntu-latest
        steps:
        - name: slack-send
          uses: slackapi/slack-github-action@v1.24.0
          with:
            # Slack channel ID where message will be posted. Needed if using bot token
            channel-id: 'C057RHL9RTL'
            # Message to post into Slack. Needed if using bot token
            slack-message: "GitHub tests result: ${{ job.status }}\n${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            # ${{ github.event.pull_request.html_url || github.event.head_commit.url }
          env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
