name: Update models

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "dev" branch
  push:
    branches: [ "dev", "workflow-tests" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            # Fetch all last commits
            fetch-depth: 0 

        - name: Setup Python
          uses: actions/setup-python@v3.1.4
          with:
            python-version: 3.11.3
            
        - name: Get changed threat models 
          id: changed-files-specific
          uses: tj-actions/changed-files@v36
          with:
            files: ./*.json
        - name: Update models hash and date
          run: |
            python3 update-models.py ${{ steps.changed-files-specific.outputs.all_changed_files }}

          # Commit and Push wiki and modified models
        - name: Commit & Push changes
          uses: actions-js/push@master
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            branch: dev
