name: Update wiki

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "dev" branch
  push:
    branches: [ "dev", "workflow-tests" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Setup Python
          uses: actions/setup-python@v3.1.4
          with:
            python-version: 3.11.3
        
        - name: Checkout wiki repo
          uses: actions/checkout@v3
          with:
            repository: edamametechnologies/threatmodels.wiki
            token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
        
        - name: Checkout threatmodel repo to get the python script
          uses: actions/checkout@v3
          with:
            repository: edamametechnologies/threatmodels
        
        - name: Generate wiki files
          run: |
            pip install mdutils
            python3 build-wiki.py

        - name: Generate wiki files
          run: git pull --rebase
            
        - name: GitHub Commit & Push
          uses: actions-js/push@v1.4
          with:
            # Token for the repo. Can be passed in using $\{{ secrets.GITHUB_TOKEN }}
            github_token: ${{ secrets.GITHUB_TOKEN }}
            # Email used to configure user.email in `git config`.
            repository: edamametechnologies/threatmodels.wiki
            branch: master
