name: Daily Blacklists Database Update
on:
  schedule:
    # Run daily at 01:00 UTC
    - cron: '0 1 * * *'
  workflow_dispatch:  # Allow manual triggering

# Auto cancel previous runs if they were not completed.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Write permissions are required to create branches and PRs
permissions: write-all

jobs:
  update-blacklists-db:
    runs-on: ubuntu-latest
    outputs:
      outcome: ${{ steps.blacklists.outcome }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.11.3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Update blacklists database
        id: blacklists
        run: |
          echo "Running blacklists database update..."
          python3 src/iplists/build-blacklists.py
        continue-on-error: true

      - name: Upload blacklists database
        uses: actions/upload-artifact@v4
        with:
          name: blacklists-db
          path: |
            blacklists-db.json
            blacklists-db.sig
          if-no-files-found: warn

  process-results:
    needs: [update-blacklists-db]
    runs-on: ubuntu-latest
    steps:

      - name: Setup EDAMAME Posture
        uses: edamametechnologies/edamame_posture_action@v0
        with:
          edamame_user: ${{ vars.EDAMAME_POSTURE_USER }}
          edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
          edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
          edamame_id: ${{ github.run_id }}
          checkout: true

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history
      
      - name: Download blacklists database
        uses: actions/download-artifact@v4
        with:
          name: blacklists-db
          path: .
      
      - name: Setup Python
        uses: actions/setup-python@v3.1.4
        with:
          python-version: 3.11.3
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Validate blacklists database
        id: validate_blacklists
        run: |
          echo "Validating blacklists database..."
          python3 src/publish/validate-models.py blacklists-db.json
        continue-on-error: true
      
      - name: Configure git
        run: |
          # Configure git
          git config --global user.email "dev@edamame.tech"
          git config --global user.name "EDAMAME Dev"

      - name: Check for changes
        id: check_changes
        run: |
          if [[ $(git status --porcelain | grep -E 'blacklists-db\.(json|sig)') ]]; then
            echo "changes=true" >> $GITHUB_OUTPUT
            echo "Changes detected in blacklists database files"
          else
            echo "changes=false" >> $GITHUB_OUTPUT
            echo "No changes detected in blacklists database files"
          fi

      - name: Commit and push changes directly to main
        if: |
          needs.update-blacklists-db.outputs.outcome == 'success' && 
          steps.check_changes.outputs.changes == 'true'
        run: |
          # Add the updated files
          git add blacklists-db.json blacklists-db.sig
          
          # Commit the changes
          git commit -m "Daily update of blacklists database [skip ci]"
          
          # Push directly to main
          git push origin HEAD:main
          
          echo "Successfully updated blacklists database and pushed changes to main"

      - name: Send failure notification
        if: needs.update-blacklists-db.outputs.outcome == 'failure'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C072J0U9TH7'
          slack-message: |
            GitHub blacklists database update workflow failed:
            Blacklists update: ${{ needs.update-blacklists-db.outputs.outcome }}
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Send success notification
        if: |
          needs.update-blacklists-db.outputs.outcome == 'success' && 
          steps.check_changes.outputs.changes == 'true'
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: 'C07127YECN4'
          slack-message: |
            GitHub blacklists database update workflow successful:
            - Updated blacklists database
            - Committed directly to main branch
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }} 