name: Update wiki

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Setup Python
          uses: actions/setup-python@v3.1.4
          with:
            python-version: 3.11.3
        
        - name: Checkout threatmodel repo to get the python script
          uses: actions/checkout@v3
        
        - name: Generate wiki files
          run: |
            pip install -r requirements.txt
            python3 src/wiki/build-wiki.py

        - name: Clone wiki
          run: |
            mkdir -p /tmp/wiki/
            git clone https://${{ secrets.GITHUB_TOKEN }}@github.com/edamamedev/threatmodels.wiki.git /tmp/wiki
          
        - name: Move files to the wiki repo
          run: |
            cp *.md /tmp/wiki/
            
        - name: Push to wiki
          run: |
            cd /tmp/wiki
            git config user.email "dev@edamame.Tech"
            git config user.name "Edamame Dev"
            git add .
            git commit -m "docs: Updated wiki files"
            git push