name: Update wiki

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:

        - name: Setup EDAMAME Posture
          uses: edamametechnologies/edamame_posture_action@v0
          with:
            edamame_user: ${{ vars.EDAMAME_POSTURE_USER }}
            edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
            edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
            edamame_id: ${{ github.run_id }}
            checkout: true
            # We need to wait for the API access to be granted as we require protected access
            wait_for_api: true

        - name: Setup Python
          uses: actions/setup-python@v3.1.4
          with:
            python-version: 3.11.3
        
        - name: Generate wiki files
          run: |
            pip install -r requirements.txt
            python3 src/wiki/build-wiki.py

        - name: Clone wiki
          run: |
            mkdir -p /tmp/wiki/
            git clone https://${{ secrets.DEV_GITHUB_TOKEN }}@github.com/edamametechnologies/threatmodels.wiki.git /tmp/wiki
          
        - name: Move files to the wiki repo
          run: |
            cp *.md /tmp/wiki/
            
        - name: Push to wiki
          run: |
            cd /tmp/wiki
            git config --global user.email "dev@edamame.tech"
            git config --global user.name "EDAMAME Dev"
            git add .
            # Try to commit. If it fails (non-zero exit code), it means no changes.
            # If it succeeds (zero exit code), then push.
            if git commit -m "docs: Updated wiki files"; then
              echo "Changes committed, pushing to wiki..."
              git push
            else
              echo "No changes to commit to wiki."
              # Exit with 0 to indicate success (no push needed/attempted)
              exit 0
            fi

        - name: Slack reports
          if: success() # Only report success if the job succeeded
          uses: slackapi/slack-github-action@v1.26.0
          with:
            channel-id: 'C07127YECN4'
            slack-message: "GitHub threat models wiki updated from branch ${{ github.ref }} - see: https://github.com/edamametechnologies/threatmodels/wiki"
          env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

        - name: Slack failure report
          if: failure() # Report if any step failed
          uses: slackapi/slack-github-action@v1.26.0
          with:
            channel-id: 'C072J0U9TH7'
            slack-message: "FAILED: GitHub threat models wiki update from branch ${{ github.ref }}. Check workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}