name: Update wiki

on:
  # Triggers the workflow on push events but only for the "main" branch
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

        - name: Setup EDAMAME Posture
          uses: edamametechnologies/edamame_posture_action@v0
          with:
            edamame_user: ${{ vars.EDAMAME_POSTURE_USER }}
            edamame_domain: ${{ vars.EDAMAME_POSTURE_DOMAIN }}
            edamame_pin: ${{ secrets.EDAMAME_POSTURE_PIN }}
            edamame_id: ${{ github.run_id }}
            checkout: true

        - name: Setup Python
          uses: actions/setup-python@v3.1.4
          with:
            python-version: 3.11.3
        
        - name: Generate wiki files
          run: |
            pip install -r requirements.txt
            python3 src/wiki/build-wiki.py

        - name: Clone wiki
          run: |
            mkdir -p /tmp/wiki/
            git clone https://${{ secrets.DEV_GITHUB_TOKEN }}@github.com/edamametechnologies/threatmodels.wiki.git /tmp/wiki
          
        - name: Move files to the wiki repo
          run: |
            cp *.md /tmp/wiki/
            
        - name: Push to wiki
          run: |
            cd /tmp/wiki
            git config user.email "dev@edamame.tech"
            git config user.name "EDAMAME Dev"
            git add .
            git commit -m "docs: Updated wiki files"
            git push

        - name: Slack reports
          uses: slackapi/slack-github-action@v1.26.0
          with:
            channel-id: 'C07127YECN4'
            slack-message: "GitHub threat models wiki updated from branch ${{ github.ref }} - see: https://github.com/edamametechnologies/threatmodels/wiki"
          env:
              SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}